version: '2.1'

networks:
  servers:

services:

  balancer:
    environment:
      - CONF_RESPONSE_DELAY_SEC=1
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    environment:
      - CONF_RESPONSE_DELAY_SEC=2
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    environment:
      - CONF_RESPONSE_DELAY_SEC=2
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
