FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

# TODO: Змініть на власну реалізацію системи збірки
RUN go get -u github.com/mdapathy/arch-design-2/build/cmd/boodtdma

WORKDIR /go/src/practice-3
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
WORKDIR ./integration
RUN CGO_ENABLED=0
ENTRYPOINT ["boodtdma"]
